export interface Project {
  slug: string;
  name: string;
  subtitle: string;
  year: string;
  url?: string;
  featured?: boolean;
  /** One-line summary used on cards. */
  summary: string;
  problem: string;
  approach: string;
  systems: string[];
  outcome: string;
  tags: string[];
}

/**
 * Engineering work, sourced from Andrew Riefenstahl's public portfolio and
 * project history. No employers, clients, metrics, or technologies are
 * included beyond what is already publicly documented.
 */
export const projects: Project[] = [
  {
    slug: "flockx",
    name: "Fetch.ai / Flockx",
    subtitle: "AI agent workflow platform",
    year: "2022–present",
    url: "https://agents.flockx.io",
    featured: true,
    summary:
      "LangGraph agent orchestration and RAG-powered chat over WebSocket on an AI agent platform.",
    problem:
      "The platform needed conversational agents that could reason over a knowledge base in real time, along with the API, auth, and data plumbing to support them.",
    approach:
      "Architected LangGraph-based agent orchestration with RAG-powered chat over WebSocket. Built API routes, authentication systems, and data transformation pipelines, then worked on performance optimization, database migrations, and search.",
    systems: [
      "LangGraph / LangChain",
      "Next.js",
      "FastAPI",
      "Django ORM",
      "Redis Streams",
      "Elasticsearch",
      "AWS S3",
      "Auth0",
    ],
    outcome:
      "Agent orchestration, streaming chat, and third-party integrations shipped into an ongoing production product.",
    tags: ["AI agents", "RAG", "Backend", "APIs", "AWS"],
  },
  {
    slug: "whole-earth-curriculum",
    name: "Whole Earth Curriculum",
    subtitle: "Open-source K–12 curriculum",
    year: "2026",
    url: "https://wholeearthcurriculum.org",
    featured: true,
    summary:
      "An open-source K–12 curriculum generated by an agent loop across nearly two billion tokens.",
    problem:
      "Producing a complete, coherent K–12 curriculum by hand is prohibitively slow and expensive.",
    approach:
      "Built an agent loop that generates and reconciles curriculum content, using a cost-efficient model to make near-two-billion-token generation affordable. Published the result as an open-source Astro site.",
    systems: ["Agent loop", "DeepSeek", "Astro", "Open source"],
    outcome:
      "A free, open-source K–12 curriculum published at wholeearthcurriculum.org.",
    tags: ["AI agents", "Automation", "Open source", "Astro"],
  },
  {
    slug: "iscpo",
    name: "ISCPO.org",
    subtitle: "Membership platform & editorial system",
    year: "2025–present",
    url: "https://iscpo.org",
    featured: true,
    summary:
      "A WordPress membership platform re-architected for reproducible environments and lower config drift.",
    problem:
      "The organization relied on native WordPress editorial workflows but needed reproducible environments and less configuration drift across them.",
    approach:
      "Architected the platform with Sage 11, Acorn 5, and Blade, keeping a disciplined plugin/theme boundary so editors kept the WordPress experience while the codebase gained Laravel-style structure. Added a GitHub Actions pipeline.",
    systems: [
      "WordPress",
      "Sage 11 / Acorn 5 / Blade",
      "Tailwind CSS",
      "Alpine.js",
      "Memberful",
      "GitHub Actions",
    ],
    outcome:
      "A membership platform that preserves the WordPress editing workflow while making key site structure reproducible across environments.",
    tags: ["Architecture", "WordPress", "Membership", "CI/CD"],
  },
  {
    slug: "propane",
    name: "Propane.com",
    subtitle: "Enterprise website",
    year: "2021",
    url: "https://propane.com",
    featured: true,
    summary:
      "Enterprise web property with Okta 2FA, Algolia search, HubSpot CRM, and an automated release pipeline.",
    problem:
      "An enterprise marketing site needed secure authentication, fast search, CRM integration, and a dependable release process.",
    approach:
      "Built advanced WordPress customizations and stateful web applications, implemented CI, added OAuth/Okta two-factor authentication, integrated Algolia search and HubSpot CRM, and optimized React components.",
    systems: [
      "WordPress",
      "React",
      "OAuth / Okta",
      "CI/CD",
      "Algolia",
      "HubSpot",
    ],
    outcome:
      "An enterprise web property with secure sign-in, integrated search and CRM, and an automated release pipeline.",
    tags: ["Enterprise", "Auth", "Search", "CI/CD", "Integrations"],
  },
  {
    slug: "abowlofred",
    name: "ABowlofRed.com",
    subtitle: "Nonprofit charity platform",
    year: "2021–present",
    url: "https://abowlofred.com",
    featured: true,
    summary:
      "Charity site with Stripe ticketing, migrated from Gatsby to Astro for performance and developer experience.",
    problem:
      "The site needed faster performance and a better developer workflow while continuing to sell event tickets reliably.",
    approach:
      "Migrated the Gatsby frontend to Astro, kept content in Strapi CMS on AWS EC2 with Node.js, and maintained Stripe-backed ticketing.",
    systems: ["Astro", "Strapi CMS", "AWS EC2", "Node.js", "Stripe"],
    outcome:
      "Stripe ticketing supporting more than $130,000 in annual ticket sales, on a faster and easier-to-maintain frontend.",
    tags: ["Payments", "Migration", "Performance", "CMS"],
  },
  {
    slug: "mcp-server-suite",
    name: "MCP Server Suite",
    subtitle: "Open-source AI tooling",
    year: "2025–present",
    url: "https://github.com/riefer02",
    featured: true,
    summary:
      "Safety-first MCP servers giving AI assistants governed, read-only access to real systems.",
    problem:
      "AI assistants need access to real data and systems without becoming a security or cost liability.",
    approach:
      "Built safety-first MCP servers for PostgreSQL, MySQL, and Mezmo log retrieval with read-only, quota-conscious, auditable access, plus work on Godot tooling for AI-assisted game development.",
    systems: ["MCP", "Python", "TypeScript", "PostgreSQL", "MySQL", "Docker"],
    outcome:
      "Open-source tools designed to be auditable and hard to misuse, published on GitHub.",
    tags: ["AI tooling", "MCP", "Databases", "Security", "Open source"],
  },
  {
    slug: "tolberts",
    name: "Tolbert's Restaurant",
    subtitle: "Restaurant site & integrations",
    year: "2024",
    url: "https://tolbertsrestaurant.com",
    summary:
      "Performance-focused restaurant site on Astro with a headless WordPress backend and third-party integrations.",
    problem:
      "The restaurant needed a fast site connected to its existing content and third-party ordering and menu systems.",
    approach:
      "Built an Astro frontend against headless WordPress, added custom API routes for menu and ordering integrations, plus calendar and contact forms, with accessibility and performance held as requirements.",
    systems: [
      "Astro",
      "Headless WordPress",
      "Custom API routes",
      "Third-party integrations",
    ],
    outcome:
      "A fast, accessible restaurant site with live menu, ordering, and calendar integrations.",
    tags: ["Astro", "Headless CMS", "APIs", "Integrations"],
  },
  {
    slug: "chisos",
    name: "Chisos",
    subtitle: "AI note-taking & speech platform",
    year: "2025",
    url: "https://chisos.xyz",
    summary:
      "Full-stack AI note-taking app with speech-to-text, secure auth, and provisioned infrastructure.",
    problem:
      "Capture spoken notes and organize them automatically, without the user managing servers or infrastructure.",
    approach:
      "Developed, deployed, and provisioned a speech-to-text note-taking app on Railway, added Clerk authentication, and integrated AI services for transcription and organization. Built with Vite and TanStack Router.",
    systems: ["Vite", "TanStack Router", "OpenAI", "Clerk", "Railway"],
    outcome:
      "A deployed full-stack application with secure authentication and AI-powered note organization.",
    tags: ["AI applications", "Full-stack", "Auth", "Infrastructure"],
  },
  {
    slug: "concert-on-lake-grapevine",
    name: "The Concert on Lake Grapevine",
    subtitle: "Nonprofit event site",
    year: "2026",
    url: "https://theconcertonlakegrapevine.com",
    summary:
      "Charity concert site with Stripe-powered ticketing for a nonprofit event.",
    problem:
      "A one-day charity event needed an informative site and dependable online ticketing.",
    approach:
      "Co-developed and produced the site covering lineup, FAQ, and sponsors, with Stripe-powered ticketing.",
    systems: ["Stripe", "Ticketing", "Nonprofit event site"],
    outcome: "A live event site with Stripe ticketing for the concert.",
    tags: ["Payments", "Web", "Nonprofit"],
  },
  {
    slug: "steel-calculator",
    name: "Steel Calculator",
    subtitle: "Focused microservice web app",
    year: "2022",
    url: "https://steelcalculator.xyz",
    summary:
      "A focused web app used daily by a steel-industry professional.",
    problem:
      "A steel-industry professional needed a fast, focused tool for daily calculations.",
    approach:
      "Built a small, purpose-built web application with plain JavaScript, HTML, and CSS.",
    systems: ["Vite", "JavaScript", "HTML / CSS"],
    outcome:
      "A tool in active daily use — proof that the most valuable software is often the least flashy.",
    tags: ["Web app", "Frontend"],
  },
];

export const featuredProjects = projects.filter((project) => project.featured);
